# Generated by Django 3.2.6 on 2021-08-23 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FileUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trade_code', models.CharField(blank=True, max_length=255, null=True)),
                ('high', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('low', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('open', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('close', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('volume', models.CharField(blank=True, max_length=255, null=True)),
                ('date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
